# Generated by Django 5.1.7 on 2025-05-31 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abstractfoodgramuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='abstractfoodgramuser',
            name='user_permissions',
        ),
    ]
