# Generated by Django 5.1.7 on 2025-05-31 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_abstractfoodgramuser_groups_and_more'),
        ('foodgram_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='foodgram_user.abstractfoodgramuser', verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to='foodgram_user.abstractfoodgramuser', verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower', to='foodgram_user.abstractfoodgramuser', verbose_name='Подписчик'),
        ),
        migrations.AlterField(
            model_name='favouritesrecipes',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='foodgram_user.abstractfoodgramuser', verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='shoppinglist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_list', to='foodgram_user.abstractfoodgramuser', verbose_name='Пользователь'),
        ),
        migrations.DeleteModel(
            name='AbstractFoodgramUser',
        ),
    ]
